[package]
edition = "2018"
name = "ipcd"
version = "0.1.0"

[dependencies]
libredox = "0.0.3"
redox-daemon = "0.1.2"
redox_syscall = "0.4.1"
redox-scheme = { git = "https://gitlab.redox-os.org/redox-os/redox-scheme.git" }
redox_event = "0.2.0"
